DROP DATABASE IF EXISTS authen;
CREATE DATABASE authen CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE authen;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
